### ISSUE TITLE
ModuleNotFoundError python enviroment

### ISSUE THREAD

**Issue by nocomp** [MCMH2000/yardattack#1]
hi,
thx a lot for this gret tool
i am having an issue with a module that is installed but not found, hope you can help

nocomp@zebox:~/tools/sdr/yardattack$ sudo python3 yardattack.py -c store-down -f 433900000 -b 9600 -m MOD_ASK_OOK -s 30
[sudo] Mot de passe de nocomp : 
Traceback (most recent call last):
  File "yardattack.py", line 6, in <module>
    import bitstring
ModuleNotFoundError: No module named 'bitstring'

but bitstring is installed:

nocomp@zebox:~/tools/sdr/yardattack$ pip install bitstring
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bitstring in /home/nocomp/.local/lib/python3.8/site-packages (3.1.7)

any suggestions?

best regards

**Comment by MCMH2000** [comment]
Do you have more than one python enviroment? (python3 and python 2.7 for example).
If yes, you have installed the module with pip to the python enviroment, but you need to install it with pip3 to the python3 enviroment because you have to use python3 to execute it.
So try: pip3 install bitstring

**Comment by MCMH2000** [comment]
Oh, I forgot that this was developed with python2, so maybe try executing yardattack with python instead of python3

**Comment by nocomp** [comment]
hi, thx for your reply,
i ve tried pip3 cause i thougth like you, but no luck, and trying with python, same type of error with different module, weird
nocomp@zebox:~/tools/sdr/yardattack$ pip3 install bitstring
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bitstring in /home/nocomp/.local/lib/python3.8/site-packages (3.1.7)
nocomp@zebox:~/tools/sdr/yardattack$ sudo python3 yardattack.py -c store-down -f 433900000 -b 9600 -m MOD_ASK_OOK -s 30
[sudo] Mot de passe de nocomp : 
Traceback (most recent call last):
  File "yardattack.py", line 6, in <module>
    import bitstring
ModuleNotFoundError: No module named 'bitstring'
nocomp@zebox:~/tools/sdr/yardattack$ sudo python yardattack.py -c store-down -f 433900000 -b 9600 -m MOD_ASK_OOK -s 30
Traceback (most recent call last):
  File "yardattack.py", line 7, in <module>
    import configparser
ImportError: No module named configparser
nocomp@zebox:~/tools/sdr/yardattack$ pip install configparser
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: configparser in /home/nocomp/.local/lib/python3.8/site-packages (3.8.1)
nocomp@zebox:~/tools/sdr/yardattack$

**Comment by MCMH2000** [comment]
Ok, than it is definitely a permission issue.
"Defaulting to user installation because normal site-packages is not writeable"
pip can't install it to the location where it should.

try:
sudo python -m pip install [package_name]

Also "sudo" has an impact on the installation.

**Comment by nocomp** [comment]
yeaaaaaaaaaaaaaaaaaaa all ok

nocomp@zebox:~/tools/sdr/yardattack$ sudo python yardattack.py -c store-down -f 433900000 -b 9600 -m MOD_ASK_OOK -s 30
